const spiritualLaws = [
  {
    name: "The Law of Pure Potentiality",
    explanation:
      "The Law of Pure Potentiality teaches that our essential nature is pure consciousness — an infinite field of all possibilities, creativity, and joy. At the core, you are not your ego, job title, or social identity. You are pure spirit, eternal and unbounded, connected to everything and everyone.",
    why: "By connecting with your true self through silence and meditation, you tap into the infinite source of creativity and possibilities. This allows you to manifest your desires with effortless ease.",
    access:
      "- Shift from object-referral (ego-based, fear-driven, dependent on external validation) to self-referral (spirit-based, fearless, free from the need for control).<br>" +
      "- Embrace silence, meditation, non-judgment, and communion with nature.<br>" +
      "- In this state of stillness, even the smallest intention ripples into creation, effortlessly manifesting desires through the creative mind of the universe.",
    tasks: [
      "Spend 30 minutes in silence today, just observing your thoughts without judgment.",
      "Meditate for 15-20 minutes focusing on your breath and becoming the observer.",
      "Go for a walk in nature and immerse yourself in its intelligence without labeling anything.",
      "Practice non-judgment for one hour today—release all labels of good or bad.",
      "Write down three negative self-judgments and reframe them with love and acceptance.",
      "Turn off all digital devices for one hour and simply Be.",
      "Observe the stars or sky at night in complete silence and awe.",
      "Take five deep breaths every hour and return to presence.",
      "Listen to calming music with your eyes closed and feel it with your whole being.",
      "Say nothing for an entire morning or evening and observe how it feels.",
      "Take a bath or shower mindfully, feeling gratitude for your body.",
      "Sit with a candle and meditate on its flame for 10 minutes.",
      "Smile at every person you see today as a silent blessing.",
      "Repeat a mantra while walking slowly in nature.",
      "Lie under the sky and imagine your body dissolving into light.",
      "Eat one meal in complete silence, chewing mindfully.",
      "Spend 5 minutes focusing on the space between your thoughts.",
      "Practice gratitude for 10 minutes in complete silence.",
      "Watch an animal or insect and observe its still presence.",
      "Journal about who you are beyond your name, role, or identity.",
      "Look into the mirror and say 'I am not this form, I am the formless essence.'",
      "Observe your reactions during the day—are they ego or essence-based?",
      "Create art, write, or move freely without purpose or judgment.",
      "Lie on the ground and feel the Earth supporting you.",
      "Visualize light radiating from your heart into the world.",
      "Let go of one thing you feel the need to control today.",
      "Read something spiritual in silence and reflect without analysis.",
      "Avoid mirrors and appearances for the whole day.",
      "Give someone a silent blessing without telling them.",
      "Take a long pause before speaking every time you talk today.",
      "Forgive someone in your heart and send them love silently.",
      "Speak gently and with conscious awareness today.",
      "Spend an hour doing nothing—no reading, scrolling, or listening.",
      "Say ‘I surrender’ whenever you feel tension today.",
      "Touch a tree or plant and feel its silent intelligence.",
      "Draw or paint with no outcome in mind—just presence.",
      "End your day with 10 minutes of complete stillness.",
      "Light incense, sage, or a candle and breathe deeply with it.",
      "Journal a dialogue with your higher Self—ask questions, receive answers.",
      "Do something creative without sharing it with anyone.",
      "Be in a space of nature at sunrise or sunset.",
      "Spend 10 minutes listening deeply to another without interrupting.",
      "Carry a stone or crystal and use it as a grounding anchor.",
      "Choose a 2-hour block of your day to practice total awareness.",
      "Imagine a beam of light above your head connecting you to source.",
      "Reflect on one fear and say ‘I am not this fear, I am freedom.’",
      "Avoid multitasking all day—do one thing at a time, with full presence.",
      "Sit still and listen to the ambient sounds around you without resistance.",
      "Create a small altar or sacred space and sit quietly with it.",
      "Speak lovingly to your body and thank it for carrying your soul.",
      "Write a love letter to your own soul.",
      "Close your eyes and visualize yourself melting into the universe.",
    ],
    mantras: [
      "I am infinite possibilities.",
      "In my essence, I am pure consciousness.",
      "I am not my thoughts, emotions, or roles.",
      "Stillness is my true power.",
      "I am one with the universe.",
      "I exist beyond fear, judgment, or limitation.",
      "I am the silent observer.",
      "My nature is boundless joy and creativity.",
      "I am the field of all potential.",
      "I am awareness itself.",
      "I honor the divinity that resides within me.",
      "I trust the flow of the universe.",
      "I release control and return to presence.",
      "I am the space between my thoughts.",
      "Peace begins within me.",
      "I surrender to the wisdom of the Self.",
      "In stillness, I remember who I am.",
      "My being is eternal and unchanging.",
      "I am light in human form.",
      "I receive and radiate love effortlessly.",
      "I rest in my natural state of awareness.",
      "I do nothing, and everything is done.",
      "I embrace the silence within me.",
      "My soul knows the way.",
      "I let go of all that I am not.",
      "I am whole and complete as I am.",
      "My power is presence.",
      "Each moment is sacred and full of potential.",
      "I listen to the voice within.",
      "All things are possible through me.",
      "My attention creates my reality.",
      "I am not separate from life—I am life.",
      "Love is my nature.",
      "Silence is the language of my soul.",
      "I am aligned with universal intelligence.",
      "I breathe in peace, I breathe out resistance.",
      "My spirit is expansive and free.",
      "I am grounded in divine presence.",
      "I receive the abundance of the universe.",
      "I am deeply connected to all that is.",
      "Nothing outside defines me.",
      "I move through life with grace and ease.",
      "The entire cosmos exists within me.",
      "I am awareness witnessing itself.",
      "Presence is my highest power.",
      "I see through the eyes of spirit.",
      "I walk in beauty, peace, and truth.",
      "My true self is timeless and fearless.",
      "I dissolve all illusions of separation.",
      "I am Source energy in motion.",
    ],
  },
  {
    name: "The Law of Giving",
    explanation:
      "The Law of Giving, also known as the Law of Giving and Receiving, is based on the understanding that the universe operates through dynamic exchange. Just as your body, mind, and spirit are in constant interaction with the cosmos, energy must continually flow to remain alive and vital. Giving and receiving are two sides of the same coin, part of the eternal rhythm of life. When you give freely and joyfully, you align yourself with the abundant flow of the universe.",
    why: "Everything in the universe flows—energy, money, love, and attention. When we hold back or hoard, we block this flow and invite stagnation. But when we give from the heart, whether it's a smile, a prayer, or a tangible gift, we keep the circulation of abundance alive in our lives. The intention behind your giving is everything: give to create joy, and you will experience joy in return.",
    access:
      "- Make it a habit to give something—big or small—every time you meet someone. This can be a compliment, a flower, or a silent blessing.<br>" +
      "- Be open to receiving with gratitude. Accept gifts from life and others, whether it's kindness, sunlight, or a smile.<br>" +
      "- Practice giving and receiving not just material things, but life's most precious gifts: love, appreciation, attention, and compassion.",
    tasks: [
      "Give a sincere compliment to three people today.",
      "Offer a small gift to someone you care about—a flower, a note, or a thoughtful gesture.",
      "Silently bless every person you pass today, wishing them joy and happiness.",
      "Practice receiving with gratitude—smile and say thank you when someone offers you help or kindness.",
      "Write a loving message or letter to someone who made a difference in your life.",
      "Donate something today—money, time, energy, or attention—to a cause or person in need.",
      "Notice what life is offering you today: the warmth of the sun, the taste of food, the presence of loved ones.",
      "Surprise someone with a random act of kindness.",
      "Smile at everyone you meet today and really mean it.",
      "Call someone just to tell them you appreciate them.",
      "Practice giving without expecting anything in return.",
      "Make or buy a small gift and give it to a stranger anonymously.",
      "Help someone without them asking—hold a door, carry something, offer support.",
      "Give your full presence and undivided attention in one conversation today.",
      "Share something of value—a book, a resource, or advice—with someone who needs it.",
      "Leave a kind note in a public place for someone to find.",
      "Offer a prayer or silent blessing for someone who is struggling.",
      "Forgive someone in your heart and send them love.",
      "Reflect on what gifts you already have to offer the world.",
      "Give thanks out loud for three things you receive today.",
      "Plant a seed or a tree as a gift to the Earth.",
      "Offer your talents or time to help someone without being asked.",
      "Bake or cook something and share it with neighbors or coworkers.",
      "Bless your food before eating, recognizing it as a gift.",
      "Listen deeply to someone without interrupting or advising.",
      "Support a local artist or small business as a gesture of exchange.",
      "Share your knowledge or skills with someone who can benefit from them.",
      "Create a piece of art or writing and give it away.",
      "Write a list of ten things you can give that cost nothing.",
      "Intend to uplift every person you meet today in some small way.",
    ],
    mantras: [
      "I give freely, and I receive abundantly.",
      "I am a conduit for universal flow.",
      "My giving creates joy for others and for myself.",
      "I am open to receiving life’s blessings.",
      "Generosity expands my heart.",
      "I trust that the more I give, the more I receive.",
      "I give with love, and love returns to me.",
      "I bless everyone I meet with joy and peace.",
      "My giving multiplies abundance in the world.",
      "The universe supports my giving with infinite supply.",
      "I am deeply grateful for all that I receive.",
      "I share my light freely and effortlessly.",
      "Each act of giving ripples through the universe.",
      "I radiate appreciation and warmth.",
      "I give to uplift, and I receive in grace.",
      "Today I give with intention and joy.",
      "I receive with an open heart and a grateful soul.",
      "Love, abundance, and kindness flow through me.",
      "I give because it is my nature to share.",
      "I celebrate the joy of giving and receiving.",
      "My heart overflows with generosity.",
      "Every encounter is an opportunity to give.",
      "I am the source and the recipient of kindness.",
      "My presence is a gift to the world.",
      "I live in harmony with the law of circulation.",
      "All that I give returns to me multiplied.",
      "I offer blessings to all beings, silently and lovingly.",
      "Giving is my way of expressing abundance.",
      "I offer my gifts with humility and love.",
      "The universe responds to my generosity.",
    ],
  },
  {
    name: "The Law of Karma",
    explanation:
      "The Law of Karma, or the Law of Cause and Effect, reminds us that every action generates energy that returns to us in like kind. Karma is both the action and the consequence, simultaneously. Every choice we make shapes our reality. By becoming conscious choice-makers, we empower ourselves to create happiness, success, and evolution—not only for ourselves, but for everyone affected by our actions.",
    why: "Life is a constant stream of choices, and most are made unconsciously through conditioned responses. Karma teaches us to pause and reflect—to become aware of our intentions and their potential impact. When we choose actions that bring happiness and fulfillment to ourselves and others, we align with spontaneous right action—the path of least resistance and highest good.",
    access:
      "- Become aware of your choices in each moment—witness them as they arise.<br>" +
      "- Ask yourself: 'What are the consequences of this choice?' and 'Will it bring happiness to me and others?'<br>" +
      "- Tune into your body—especially your heart—for messages of comfort or discomfort as intuitive guidance.",
    tasks: [
      "Before making a decision today, pause and ask: 'Will this bring happiness to me and others?'",
      "Journal about a recurring pattern in your life—what unconscious choices might be causing it?",
      "Consciously choose your response in a situation where you'd normally react habitually.",
      "Reflect on a past challenging event and write about the lesson or opportunity it contained.",
      "Meditate on your heart center and ask for intuitive guidance regarding a current life choice.",
      "Observe your reactions during the day—are they based on old conditioning?",
      "Write a list of your most frequent emotional triggers and the choices you make in response.",
      "Before any conversation today, set the intention to speak and act with awareness and kindness.",
      "Ask yourself what karma you are creating with your actions right now.",
      "Visualize yourself making choices that lead to peace, joy, and abundance.",
      "Write down three ways you can respond more consciously to people who challenge you.",
      "Make a list of five small daily habits—are they generating positive or negative karma?",
      "Consciously choose not to gossip or speak negatively about anyone today.",
      "Say a silent blessing for someone who has wronged you—release resentment.",
      "When feeling triggered, take three breaths and ask: 'What am I choosing right now?'",
      "Make one uncomfortable but necessary choice today that aligns with your highest good.",
      "Reflect on how your choices have shaped your present reality—what can you shift moving forward?",
      "Choose to forgive someone today, even silently, as a karmic release.",
      "Spend time in silence today and become aware of your inner dialogue and choices.",
      "Offer help or support to someone, knowing that every act of service plants seeds of good karma.",
      "Choose one limiting belief and consciously rewrite it into a new empowering narrative.",
      "Avoid blaming anyone today—instead, take full responsibility for your own energy.",
      "Practice patience in a situation where you would normally rush or react.",
      "Intentionally do one kind act without expecting anything in return.",
      "Notice your choices around food, rest, or movement—are they nurturing your future self?",
      "Express gratitude to someone whose actions positively affected your life, even if in the past.",
      "Turn off autopilot—consciously drive, eat, or walk today while remaining fully present.",
      "Reframe a current challenge as an opportunity to grow and evolve.",
      "Write a letter to your younger self, offering wisdom from your karmic journey so far.",
      "Spend 10 minutes reflecting on the karma you want to create this week.",
    ],
    mantras: [
      "I am a conscious creator of my reality.",
      "Every choice I make shapes my future.",
      "I act with awareness, and joy returns to me.",
      "I choose love over fear.",
      "Each moment offers me the chance to start anew.",
      "I align with spontaneous right action.",
      "I trust the wisdom of my heart.",
      "My past does not define me—my choices do.",
      "I create only uplifting and healing karma.",
      "I learn and grow from every experience.",
      "I take full responsibility for my energy.",
      "I am evolving through every conscious action.",
      "My awareness transforms my destiny.",
      "I plant seeds of peace with every word and deed.",
      "I choose to respond, not react.",
      "I surrender the past and step into the now.",
      "I am free from old patterns and stories.",
      "Each choice is a chance to align with my highest self.",
      "I welcome karmic lessons as stepping stones.",
      "The universe reflects the energy I put out.",
      "I create harmony through mindful decisions.",
      "I listen to the whispers of my soul.",
      "My life is a reflection of my inner choices.",
      "With each breath, I realign with my purpose.",
      "I bless the past and walk forward in grace.",
      "My heart knows the way.",
      "I choose what nourishes me and others.",
      "Right action arises naturally from stillness.",
      "I honor the sacred ripple of my actions.",
      "I live with integrity, compassion, and awareness.",
    ],
  },
  {
    name: "The Law of Least Effort",
    explanation:
      "The Law of Least Effort teaches that nature operates with effortless ease, and so can we. When we act in alignment with love, acceptance, and flow, we stop struggling and start receiving. This law reminds us that fulfillment doesn't require force—only presence, surrender, and inner alignment. By practicing acceptance, responsibility, and defenselessness, we allow our desires to manifest with grace.",
    why: "We often waste energy trying to control, convince, or resist life. This law shows that real power comes from surrender, not struggle. When we release ego-driven effort and allow life to unfold, we tap into nature’s intelligence—one that creates galaxies, seasons, and miracles without effort. Joy, success, and abundance arise naturally when we align with that flow.",
    access:
      "- Acceptance: Embrace this moment exactly as it is, without resistance.<br>" +
      "- Responsibility: Own your experience and see challenges as opportunities.<br>" +
      "- Defenselessness: Let go of the need to defend or control—stay open, flexible, and at peace.",
    tasks: [
      "Practice total acceptance today—remind yourself, 'This moment is exactly as it should be.'",
      "Notice a situation that frustrates you and shift from resistance to allowing.",
      "Write about a current challenge and identify the hidden opportunity in it.",
      "Spend 5 minutes observing nature—notice how effortlessly it functions.",
      "Let go of trying to convince someone of your viewpoint today—simply listen.",
      "Repeat silently throughout the day: 'I release the need to resist, control, or defend.'",
      "If you catch yourself blaming, pause and take responsibility instead.",
      "In a difficult interaction, choose peace over being right.",
      "Write about a moment you surrendered recently—how did it feel?",
      "Meditate on the phrase: 'Do less and accomplish more.'",
      "Choose to go with the flow in one area of your life where you’ve been forcing things.",
      "Let yourself enjoy one moment fully without trying to improve or change it.",
      "Pause before reacting today. Breathe and allow the moment to pass through you.",
      "Forgive someone silently by accepting them as they are right now.",
      "Declare your intention for something you desire, then release it without attachment.",
      "Observe a habit or behavior that stems from defensiveness. Gently let it go today.",
      "Journal about a time when doing less actually accomplished more.",
      "Spend time in silence or nature to reconnect with effortless awareness.",
      "Let go of multitasking today—do one thing at a time with full presence.",
      "Say 'yes' to life today, even in the small annoyances or unexpected moments.",
      "Choose not to argue, even if you know you're right—just smile and let it be.",
      "Think of someone who challenges you. What lesson might they be teaching you?",
      "Reflect on how much energy you've spent defending your opinions. What could you create with that energy instead?",
      "Release the need to fix someone today. Just hold space for them as they are.",
      "Enjoy doing nothing for 10 minutes—watch the sky, breathe, or simply be.",
      "Repeat this affirmation: 'The universe works effortlessly through me.'",
      "Approach today with softness instead of striving.",
      "Watch your inner voice—when it tries to control or judge, meet it with gentleness.",
      "Let go of needing a situation to be different in order to feel peace.",
      "Say to yourself: 'I flow like water—I bend, I move, I adapt, and I remain whole.'",
    ],
    mantras: [
      "I let go and trust the flow of life.",
      "I accept this moment exactly as it is.",
      "Effortless ease is my natural state.",
      "I do less and accomplish more.",
      "I am open, flexible, and free.",
      "My energy flows where love goes.",
      "I surrender control and embrace what is.",
      "I choose peace over resistance.",
      "I do not need to be right—I choose to be present.",
      "The universe works through me, not because of me.",
      "This moment is a gift, and I receive it fully.",
      "I am not here to struggle—I am here to shine.",
      "I release the need to defend or prove myself.",
      "I let go of the illusion of control.",
      "My calm presence is my greatest power.",
      "I meet life with acceptance and grace.",
      "Everything is unfolding in divine timing.",
      "I welcome the wisdom of ease.",
      "I release all resistance and flow with love.",
      "Simplicity, surrender, and stillness guide me.",
      "I no longer force—I allow.",
      "I move in harmony with nature’s rhythm.",
      "I create more by doing less.",
      "I am at peace with what is.",
      "Each breath brings me deeper into effortless being.",
      "I am enough, and this moment is enough.",
      "My spirit moves with softness and strength.",
      "I am rooted in stillness and aligned with joy.",
      "I am a vessel of effortless creation.",
      "Ease and grace are my way of life.",
    ],
  },
  {
    name: "The Law of Intention and Desire",
    explanation:
      "The Law of Intention and Desire is based on the understanding that energy and information exist everywhere in nature. At the quantum level, there is nothing other than energy and information. This quantum field is influenced by intention and desire. Through our unique nervous system, humans can consciously change the informational content that gives rise to our physical body and environment, manifesting our desires through attention and intention.",
    why: "By harnessing the power of intention with detachment, you can command the infinite organizing power of the universe to fulfill your desires effortlessly. Intention combined with present-moment awareness allows you to create your future while accepting your present.",
    access:
      "- Understand that attention energizes, and intention transforms.<br>" +
      "- Practice one-pointed intention with an unbending fixity of purpose.<br>" +
      "- Maintain life-centered, present-moment awareness while holding intentions for the future.<br>" +
      "- Release attachment to outcomes while maintaining passionate commitment to goals.<br>" +
      "- Trust in the infinite organizing power of the universe to handle the details.",
    tasks: [
      "Make a list of all your desires and carry it with you wherever you go.",
      "Review your list of desires before meditation, before sleep, and upon waking.",
      "Spend time daily slipping into the gap—the silent space between thoughts.",
      "Practice releasing your intentions in the gap without attachment to how they will unfold.",
      "Maintain a state of self-referral by not sharing your desires with those who don't share them.",
      "Practice present-moment awareness in all your actions throughout the day.",
      "When facing obstacles, refuse to let them consume your attention or intention.",
      "Set aside 10 minutes to sit in silence and plant your intentions in the field of pure potentiality.",
      "Write a journal entry about an intention you have without focusing on how it will manifest.",
      "Practice accepting the present moment exactly as it is while holding intention for the future.",
      "Take three deep breaths before making important decisions to center yourself in awareness.",
      "Choose one intention and focus on it with unbending purpose for an entire day.",
      "Practice detachment by identifying one outcome you're clinging to and mentally releasing it.",
      "Spend 15 minutes visualizing your intentions as already fulfilled without mapping the path.",
      "Notice when you become rigid about how something should unfold and consciously let go.",
      "Trust the universe by delegating a task or problem without micromanaging the solution.",
      "Identify one imaginary obstacle in your life and dissolve it through present-moment awareness.",
      "Create a visual representation or vision board of your intentions without timelines.",
      "Practice serenity amidst intensity by maintaining calm while pursuing goals with passion.",
      "Observe how your attention affects energy—notice what grows stronger when you focus on it.",
      "Spend time in nature observing its symphony of infinite correlation and organization.",
      "Write down what you're resisting in the present moment and practice accepting it fully.",
      "Meditate on the feeling of your desires already being fulfilled.",
      "Practice shifting from effort to intention in one area of your life.",
      "Observe how time is experienced differently in past, present, and future consciousness.",
      "Keep a daily record of how your intentions are manifesting in unexpected ways.",
      "Notice when you're striving or struggling and shift to intention and allowing.",
      "Practice transforming obstacles into opportunities through intention.",
      "Release the need to control how your desires come to fruition.",
      "Repeat a mantra related to intention while in meditation.",
      "Observe the silent power of intention in nature—how seeds become plants without effort.",
      "Practice one-pointed focus on a single task without distraction.",
      "Spend 5 minutes in the morning setting intentions for your day without attachment.",
      "Notice when your attention scatters and gently bring it back to your intention.",
      "Write down five ways you can surrender control while maintaining clear intention.",
      "Practice patience by trusting in the perfect timing of your intentions manifesting.",
      "Observe something in your life that manifested through intention rather than effort.",
      "Take inspired action based on inner guidance rather than external pressure.",
      "Reflect on how your current reality was shaped by past intentions and attention.",
      "Practice saying 'I intend' rather than 'I hope' or 'I'll try' when speaking of goals.",
      "Spend an evening without planning or controlling—just being and allowing.",
      "Identify where you're using force instead of intention and make a conscious shift.",
      "Practice seeing your desired outcome with such clarity that doubt disappears.",
      "Release one intention completely to the universe, trusting in perfect fulfillment.",
      "Observe how intention feels different in your body compared to willpower or effort.",
      "Practice responding to challenges with intentional clarity rather than reactive energy.",
      "Set intentions before meetings, conversations, or activities to direct their energy.",
      "Maintain unwavering focus on your intention while adapting flexibly to circumstances.",
      "Notice when fear dilutes your intention and practice returning to clear focus.",
      "Spend time contemplating how the universe orchestrates countless details effortlessly.",
      "Practice the art of allowing—creating space for your intentions to manifest naturally.",
    ],
    mantras: [
      "My intentions have infinite organizing power.",
      "I plant my desires in the fertile soil of consciousness.",
      "Attention energizes, intention transforms.",
      "I am present now, creating my future.",
      "I command the laws of nature with pure intention.",
      "My intentions orchestrate cosmic events.",
      "I release my desires to the womb of creation.",
      "Through intention, all things are possible.",
      "I am one-pointed in my intention.",
      "I maintain serenity while pursuing my desires with passion.",
      "My attention is in the present, my intention for the future.",
      "I accept the present and intend the future.",
      "The cosmic computer fulfills my intentions.",
      "My intent is desire without attachment.",
      "I trust the infinite organizing power of intention.",
      "I refuse to allow obstacles to consume my attention.",
      "My consciousness commands the laws of nature.",
      "I am unbending in my fixity of purpose.",
      "In the gap between thoughts, my intentions take root.",
      "I slip into the gap and release my desires.",
      "The universe handles the details for me.",
      "I surrender my rigid attachment to outcomes.",
      "I live in the wisdom of uncertainty.",
      "My intention combined with detachment is unstoppable.",
      "I enjoy every moment of my journey, regardless of outcome.",
      "I release my intentions into the field of all possibilities.",
      "I am grounded in the present while creating my future.",
      "My intentions emerge from pure consciousness.",
      "I am centered in awareness as I plant my desires.",
      "I trust the perfect timing of manifestation.",
      "My attention is focused and my intention is clear.",
      "I am established in self-referral, unmoved by opinions.",
      "My intentions are seeds in the fertile ground of potentiality.",
      "I maintain unwavering focus with peaceful detachment.",
      "The details of manifestation unfold perfectly without my effort.",
      "I remain in awareness while my intentions organize creation.",
      "I transform obstacles into opportunities through intent.",
      "I am connected to the field of infinite correlation.",
      "I allow my intentions to unfold in their own perfect way.",
      "My desires are communicated to the intelligence of the universe.",
      "I am patient and trusting as my intentions manifest.",
      "My intentions serve humanity and all of creation.",
      "I command the laws of nature for the benefit of all.",
      "I release control and trust the process of manifestation.",
      "My desires transform into reality through intention.",
      "I plant my intentions in the silence between thoughts.",
      "I am the co-creator of my reality through intention.",
      "I bring my attention fully to this moment.",
      "My spirit carries the consciousness of pure intention.",
      "I witness the power of my intentions manifesting with ease.",
    ],
  },
  {
    name: "The Law of Detachment",
    explanation:
      "The Law of Detachment teaches that to truly manifest our desires, we must release our attachment to the outcome. Detachment doesn't mean giving up our desires—it means holding them lightly, with trust rather than control. When we embrace uncertainty and surrender our need to predict or force outcomes, we step into the field of all possibilities. This law reminds us that true power comes from allowing, not clinging—from openness, not obsession. When we let go, we create space for creativity, surprise, and synchronicity.",
    why: "Attachment is rooted in fear and scarcity—it reflects a belief that happiness depends on specific outcomes. This belief limits us and binds us to suffering. The Law of Detachment shows us a freer way to live: by trusting the universe and embracing uncertainty, we access spontaneous solutions and fresh possibilities. This law liberates us from rigid expectations and invites joy, flexibility, and genuine growth. Detachment brings peace, while still allowing us to pursue our dreams with passion and clarity.",
    access:
      "- Surrender control—focus on your effort, not the outcome.<br>" +
      "- Embrace uncertainty as the gateway to creativity and freedom.<br>" +
      "- Practice allowing life to unfold without forcing solutions.<br>" +
      "- Trust that the universe is orchestrating events on your behalf.<br>" +
      "- See every problem as the seed of opportunity.",
    tasks: [
      "Reflect on one goal and write how it would feel to let go of needing it to happen a specific way.",
      "Notice when you’re trying to force an outcome—pause and breathe.",
      "Allow someone to be exactly who they are today without trying to change them.",
      "Let go of planning every detail today—be open to spontaneity.",
      "Spend 5 minutes contemplating the phrase: 'I trust the unknown.'",
      "Catch yourself when you say 'should'—replace it with 'could'.",
      "Write about a time when letting go brought something better than you imagined.",
      "Practice 'detached involvement'—do your best, then release the outcome.",
      "In a situation where you're unsure, say silently: 'I trust the unfolding.'",
      "Journal about an attachment you’re ready to release.",
      "Watch how nature doesn't control—it allows, flows, and adapts.",
      "Sit in stillness for 10 minutes without needing to ‘achieve’ anything.",
      "Say no to something today—not out of fear, but freedom.",
      "Make space for surprise by canceling one plan and seeing what emerges.",
      "Let go of one belief that’s keeping you stuck in fear or control.",
      "Write a list of desires and then symbolically let them go—burn or fold the list.",
      "Step into uncertainty today by trying something new without a plan.",
      "Practice not reacting immediately—pause, breathe, and observe.",
      "Think of a problem. What opportunities might be hiding inside it?",
      "Notice where you're overly attached to someone’s approval—soften your grip.",
      "Spend time watching the sky or clouds—notice their formless change.",
      "Choose to trust the process, even when you don’t see progress.",
      "Forgive someone without needing them to change or apologize.",
      "Say to yourself today: 'I am safe in the unknown.'",
      "Embrace mystery—read, watch, or experience something unpredictable.",
      "When you're disappointed, ask: 'What might be unfolding instead?'",
      "Let go of micromanaging—trust someone else to handle it today.",
      "Notice how attachment creates tension in your body—breathe it out.",
      "Write about what freedom means to you when you're unattached.",
      "Try meditation or breathwork focusing only on being, not becoming.",
      "Give up one outcome-based goal for a day—focus on joy instead.",
      "Say: 'This or something better' when thinking about your desires.",
      "Let go of the need to impress—just be your authentic self today.",
      "Avoid checking one thing you're usually compulsive about—email, socials, etc.",
      "Visualize your dream life—but then detach and trust the path.",
      "Give yourself permission to not know the next step.",
      "Find peace in doing nothing for 10 minutes—no fixing, no striving.",
      "Notice when you want to control someone's decision—release that impulse.",
      "Reflect on how much more fluid life feels when you surrender.",
      "Trust timing today instead of rushing or pushing.",
      "Do one thing with love and no expectation of return.",
      "Take a walk with no destination—just observe and wander.",
      "Shift from 'how will this happen?' to 'I trust it will unfold.'",
      "Tell yourself: 'Everything is happening *for* me, not *to* me.'",
      "Pause during stress and affirm: 'Uncertainty is my path to freedom.'",
      "Release the need for closure in one unresolved situation.",
      "See chaos not as a threat, but as potential being reorganized.",
      "Let go of multitasking—focus on being fully present.",
      "Say: 'I let go of the known, and step into the field of all possibilities.'",
      "Write about something you’re grateful for that came unexpectedly.",
      "Trust that your desire is known—your job is to allow, not chase.",
    ],
    mantras: [
      "I let go and trust in the unfolding.",
      "I release control and embrace flow.",
      "I am grounded in the wisdom of uncertainty.",
      "Detachment is my path to freedom.",
      "I do my best and let go of the rest.",
      "I trust the process of life.",
      "Everything I need comes to me in perfect timing.",
      "I let go of outcomes and live with joy.",
      "I surrender the need to know how it will happen.",
      "The unknown is where miracles are born.",
      "I am free from attachment, open to possibility.",
      "I trust that the universe knows the way.",
      "My peace does not depend on outcomes.",
      "Letting go opens the door to creation.",
      "I allow what is, and welcome what will be.",
      "I flow with life, not against it.",
      "Each moment is a mystery I celebrate.",
      "I do not cling—I create and release.",
      "I am rooted in presence, not control.",
      "Uncertainty is my ally, not my enemy.",
      "My spirit thrives in spontaneity.",
      "I release all resistance and allow miracles.",
      "I detach and expand into infinite potential.",
      "The less I force, the more I receive.",
      "I am the calm within life’s unpredictability.",
      "I let go of the past and embrace the unknown.",
      "I am aligned with the field of all possibilities.",
      "Freedom lies in detachment.",
      "I accept, allow, and adapt.",
      "All outcomes serve my highest good.",
      "I trust what is meant for me will arrive.",
      "I rest in the perfection of uncertainty.",
      "I loosen my grip and gain peace.",
      "I am unattached and deeply fulfilled.",
      "I walk in trust, not tension.",
      "Every step in the unknown brings new gifts.",
      "I welcome the magic of not knowing.",
      "I am secure in the wisdom of letting go.",
      "I act with clarity and release with grace.",
      "I meet life with soft hands and an open heart.",
      "I surrender the illusion of control.",
      "I allow life to surprise me beautifully.",
      "My soul thrives on openness and trust.",
      "I am free from needing to know the outcome.",
      "The universe handles the details for me.",
      "Letting go is an act of strength.",
      "I release, I relax, I receive.",
      "My power lies in non-attachment.",
      "I move with curiosity and confidence.",
      "Detachment makes space for wonder.",
    ],
  },
  {
    name: "The Law of Dharma (Purpose in Life)",
    explanation:
      "The Law of Dharma teaches that every person is born with a unique purpose and a divine gift meant to be shared with the world. We are not here by accident—we are spiritual beings with a mission encoded in our very essence. When we align with our true Self, discover our unique talents, and offer them in service to others, we unlock a life of meaning, joy, and spiritual abundance. This law invites us to stop asking 'What’s in it for me?' and instead ask 'How can I serve?' Through this shift, we access the deepest fulfillment available to us as humans.",
    why: "Living in alignment with our dharma leads to the deepest form of success: spiritual fulfillment and joyful service. When we lose ourselves in what we love, time disappears, and abundance naturally flows. Our true power lies not in chasing external success, but in expressing the gifts planted within us, gifts no one else can offer in the same way. By connecting with our higher self and living in service, we step into a life of passion, purpose, and peace. Dharma is not just about doing—it is about being who you truly are.",
    access:
      "- Discover your higher self through stillness, meditation, and inner awareness.<br>" +
      "- Identify your unique talents—what you love and do effortlessly.<br>" +
      "- Use your gifts to meet the needs of others.<br>" +
      "- Shift your inner dialogue from 'What can I get?' to 'How can I help?'<br>" +
      "- Trust that abundance flows when your purpose meets service.",
    tasks: [
      "Sit in silence for 10 minutes and listen inwardly—ask: 'Who am I beyond roles and labels?'",
      "Make a list of your talents and the things you love doing.",
      "Ask three people close to you what they believe your unique strengths are.",
      "Reflect on times you’ve lost track of time—what were you doing?",
      "Do one small act of service today, without expectation.",
      "Write a mission statement for your life’s purpose.",
      "Ask yourself each morning: 'How can I serve today?'",
      "Revisit something you loved doing as a child—explore it again.",
      "Spend time mentoring or helping someone with your skills.",
      "Imagine you have unlimited money and time—what would you do?",
      "Notice where you feel drained—these may not be aligned with dharma.",
      "Write about your ideal day—how much of it is aligned with your purpose?",
      "Help someone today in a way that uses one of your natural gifts.",
      "Identify a problem in the world that breaks your heart—how might you help?",
      "Journal about what brings you alive—and do more of it.",
      "Offer a service or gift freely today—just because you can.",
      "Spend time in nature and ask: 'What wants to be expressed through me?'",
      "Celebrate someone else’s gifts—acknowledge their dharma.",
      "Reflect on a compliment you often receive—how does it point to your gift?",
      "Do something today that combines your passion and service.",
      "Write about the difference between success and purpose in your life.",
      "Ask: 'What legacy do I want to leave behind?'",
      "Visualize your purpose as a flame—what fuels it?",
      "Say yes to something that lights you up, even if it scares you.",
      "Spend time in creative flow—painting, dancing, writing—then reflect.",
      "Share your story with someone—it might be your unique medicine.",
      "Reconnect with someone whose life you've impacted—reflect on how.",
      "Read or listen to a story of someone living their purpose—be inspired.",
      "Find a quote or mantra that connects you to your life’s purpose.",
      "Create a vision board for your dharma.",
      "Teach something you’re passionate about to someone else.",
      "Spend time with children—notice how they express their natural gifts.",
      "Write about your ideal contribution to the world.",
      "Ask yourself: 'If I had only one year to live, what would I do differently?'",
      "Say a prayer of gratitude for your unique gifts.",
      "Make space to do what you love today—however small.",
      "Take one small step toward a purpose-led dream.",
      "Reflect: 'Where do I feel most myself, most alive, most whole?'",
      "Do something that serves someone else using your talents.",
      "Let go of one 'should' and replace it with a soul 'yes'.",
      "Notice when you feel in flow—what were you doing or offering?",
      "Reach out to collaborate with someone on a project with heart.",
      "Trust your soul’s timing—dharma doesn’t rush.",
      "List 5 ways you can serve others using your natural abilities.",
      "Affirm: 'My life is a meaningful expression of spirit.'",
      "Notice what brings you peace—and follow it.",
      "Step into leadership in one small area where you feel called.",
      "Reflect on how your struggles have shaped your purpose.",
      "Celebrate a moment when you felt totally on-purpose.",
      "Remember: service isn’t always grand—it’s the small things done with love.",
    ],
    mantras: [
      "I am here for a reason, and I choose to live it fully.",
      "My unique gifts are needed in the world.",
      "I discover my purpose by listening to my soul.",
      "I live each day in service and love.",
      "My spirit guides me to express my highest self.",
      "When I serve, I thrive.",
      "I trust that my life has meaning and direction.",
      "I am aligned with my soul’s purpose.",
      "My life is my message.",
      "I offer my gifts freely and joyfully.",
      "My talents are divine tools for service.",
      "I wake each day ready to serve with love.",
      "I honor the sacred work of being fully myself.",
      "In giving, I receive true abundance.",
      "I am a channel for divine expression.",
      "Every act of love is part of my purpose.",
      "I walk my dharma path with courage and trust.",
      "What lights me up is meant to be shared.",
      "I am not here to compete—I am here to contribute.",
      "My joy is a signpost toward my purpose.",
      "The universe supports my highest calling.",
      "I am guided by spirit to serve humanity.",
      "I find fulfillment in meaningful contribution.",
      "Service is the gateway to abundance.",
      "I align with my truth and walk in purpose.",
      "My presence and gifts are sacred.",
      "I am enough, and I am here to give.",
      "I embrace my journey, knowing it’s sacred.",
      "My life is a sacred offering.",
      "I trust that I am being used for good.",
      "I say yes to my divine assignment.",
      "The more I serve, the more I am fulfilled.",
      "Purpose flows through everything I do.",
      "I offer myself in love, service, and authenticity.",
      "My soul’s gifts are my life’s work.",
      "I was born to shine in my own way.",
      "I follow the call of spirit with trust.",
      "My service brings joy to others and to myself.",
      "I am here to express, create, and uplift.",
      "I do what I love and serve through it.",
      "Dharma is my guide to joy and abundance.",
      "I celebrate the uniqueness of who I am.",
      "Every day is an opportunity to serve from the heart.",
      "The world needs my light and love.",
      "I am divinely equipped to fulfill my purpose.",
      "Each moment is a chance to walk in purpose.",
      "I trust the divine timing of my path.",
      "I let go of fear and follow my dharma.",
      "My purpose is unfolding with grace and power.",
    ],
  },
];

function getRandomElement(array) {
  return array[Math.floor(Math.random() * array.length)];
}

function generateAndSavePractice() {
  const selectedLaw = getRandomElement(spiritualLaws);
  const selectedTask = getRandomElement(selectedLaw.tasks);
  const selectedMantra = getRandomElement(selectedLaw.mantras);

  const content = `
    <h2>${selectedLaw.name}</h2>
    <div class="section">
      <div class="section-title">What is this law?</div>
      <div>${selectedLaw.explanation}</div>
    </div>
    <div class="section">
      <div class="section-title">To apply this law, you must:</div>
      <div>${selectedLaw.access}</div>
    </div>
    <div class="section">
      <div class="section-title">Why practice this?</div>
      <div>${selectedLaw.why}</div>
    </div>
    <div class="card">
      <div class="section-title">Today's Practice:</div>
      <div>${selectedTask}</div>
    </div>
    <div class="mantra-container">
      <div class="mantra">
        ${selectedMantra}
      </div>
    </div>
  `;

  // Save the generated content to local storage
  localStorage.setItem("dailyChallengeContent", content);

  // Display the content
  document.getElementById("law-content").innerHTML = content;

  // Scroll to top when generating new content
  window.scrollTo(0, 0);
}

// Function to load practice from local storage or generate new
function loadPractice() {
  const savedContent = localStorage.getItem("dailyChallengeContent");

  if (savedContent) {
    // If content exists in local storage, display it
    document.getElementById("law-content").innerHTML = savedContent;
  } else {
    // Otherwise, generate and save a new practice
    generateAndSavePractice();
  }
}

// Add event listener for the generate button
document
  .getElementById("generate-btn")
  .addEventListener("click", generateAndSavePractice);

// Call loadPractice on initial load, instead of generatePractice
loadPractice();

// PWA: Service Worker Registration
if ("serviceWorker" in navigator) {
  window.addEventListener("load", () => {
    navigator.serviceWorker
      .register("/service-worker.js")
      .then((registration) => {
        console.log(
          "Service Worker registered with scope:",
          registration.scope
        );
      })
      .catch((error) => {
        console.error("Service Worker registration failed:", error);
      });
  });
}
